# Generated by Django 4.2.11 on 2024-09-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genrefilmwork',
            options={'verbose_name': 'Жанр Кинопроизведения', 'verbose_name_plural': 'Жанры Кинопроизведений'},
        ),
        migrations.AlterModelOptions(
            name='personfilmwork',
            options={'verbose_name': 'Персона Кинопроизведения', 'verbose_name_plural': 'Персоны Кинопроизведений'},
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.CharField(choices=[('bla', 'Movie'), ('blabla', 'Tv Show')], default='bla', max_length=255, verbose_name='type'),
        ),
    ]
