# Generated by Django 4.2.11 on 2024-09-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_genrefilmwork_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.CharField(choices=[('movie', 'movie'), ('tv_show', 'tv_show')], default='movie', max_length=255, verbose_name='type'),
        ),
    ]
